<?php
/**
 * Plugin Name: Softkom Search Discovery
 * Description: Technical SEO, internal linking and AI/search discovery support for Softkom acquisition pages.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
function softkom_search_money_pages(){return array('ai-automation-south-africa'=>'AI Automation','business-process-automation-south-africa'=>'Business Process Automation','custom-business-systems-south-africa'=>'Custom Business Systems','ai-automation-for-smes-south-africa'=>'AI Automation for SMEs','replace-spreadsheets-manual-processes-south-africa'=>'Replace Manual Processes','sales-lead-generation-automation-south-africa'=>'Sales & Lead Automation','whatsapp-customer-service-automation-south-africa'=>'WhatsApp & Customer Service Automation','ai-readiness-assessment-south-africa'=>'AI Readiness Assessment','assessment'=>'Free AI & Systems Assessment');}
function softkom_search_money_slugs(){return array_keys(softkom_search_money_pages());}
function softkom_search_is_money_page(){return is_page()&&in_array(get_post_field('post_name',get_queried_object_id()),softkom_search_money_slugs(),true);}
function softkom_search_is_legacy_catalog(){if(is_admin())return false;$path=(string)wp_parse_url(wp_unslash($_SERVER['REQUEST_URI']??''),PHP_URL_PATH);return 0===strpos(trailingslashit($path),'/catalog/');}
function softkom_search_has_seo_plugin(){return defined('AIOSEO_VERSION')||defined('RANK_MATH_VERSION')||defined('WPSEO_VERSION')||class_exists('RankMath')||class_exists('WPSEO_Options')||function_exists('aioseo');}
add_filter('wp_robots',function($robots){if(softkom_search_is_legacy_catalog()){$robots['noindex']=true;$robots['nofollow']=true;unset($robots['index'],$robots['follow']);return $robots;}if(softkom_search_is_money_page()){unset($robots['noindex'],$robots['nofollow']);$robots['index']=true;$robots['follow']=true;$robots['max-image-preview']='large';$robots['max-snippet']=-1;$robots['max-video-preview']=-1;}return $robots;},100);
add_action('wp_head',function(){if(softkom_search_is_legacy_catalog())echo '<meta name="robots" content="noindex,nofollow,noarchive">'."\n";},0);
add_action('wp_head',function(){if(!softkom_search_is_money_page()||softkom_search_has_seo_plugin())return;echo '<link rel="canonical" href="'.esc_url(get_permalink()).'">'."\n";},2);
function softkom_search_sitemap_url(){return home_url('/softkom-sitemap.xml');}
add_action('init',function(){add_rewrite_rule('^softkom-sitemap\.xml$','index.php?softkom_acquisition_sitemap=1','top');},1);
add_filter('query_vars',function($vars){$vars[]='softkom_acquisition_sitemap';return $vars;});
function softkom_search_render_sitemap(){if(is_admin()||'1'!==(string)get_query_var('softkom_acquisition_sitemap'))return;status_header(200);nocache_headers();header('Content-Type: application/xml; charset=UTF-8');echo '<?xml version="1.0" encoding="UTF-8"?>'."\n";echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."\n";foreach(softkom_search_money_slugs() as $slug){$page=get_page_by_path($slug,OBJECT,'page');if(!$page||'publish'!==$page->post_status)continue;echo "  <url>\n";echo '    <loc>'.esc_url(get_permalink($page))."</loc>\n";$modified=get_post_modified_time('c',true,$page);if($modified)echo '    <lastmod>'.esc_html($modified)."</lastmod>\n";echo "  </url>\n";}echo "</urlset>\n";exit;}
add_action('template_redirect','softkom_search_render_sitemap',-1000);
add_filter('robots_txt',function($output,$public){if(!$public)return $output;$url=softkom_search_sitemap_url();$lines=preg_split('/\r\n|\r|\n/',trim((string)$output));$clean=array();foreach($lines as $line){if(0===stripos(trim($line),'Sitemap:'))continue;$clean[]=$line;}$clean[]='Sitemap: '.$url;return trim(implode("\n",$clean))."\n";},999,2);
add_filter('wp_sitemaps_post_types',function($types){foreach(array('catalog','product_catalog') as $type){if(isset($types[$type]))unset($types[$type]);}return $types;},100);
add_filter('the_content',function($content){if(is_admin()||!is_main_query()||!in_the_loop()||!is_page())return $content;$slug=get_post_field('post_name',get_queried_object_id());$pages=softkom_search_money_pages();if(!isset($pages[$slug])||'assessment'===$slug)return $content;$priority=array('assessment');if(false!==strpos($slug,'ai-'))$priority=array_merge($priority,array('ai-automation-south-africa','ai-automation-for-smes-south-africa','ai-readiness-assessment-south-africa'));elseif(false!==strpos($slug,'sales-'))$priority=array_merge($priority,array('business-process-automation-south-africa','ai-automation-for-smes-south-africa','custom-business-systems-south-africa'));elseif(false!==strpos($slug,'whatsapp-'))$priority=array_merge($priority,array('ai-automation-for-smes-south-africa','business-process-automation-south-africa','sales-lead-generation-automation-south-africa'));else $priority=array_merge($priority,array('business-process-automation-south-africa','custom-business-systems-south-africa','ai-automation-south-africa'));$priority=array_values(array_unique($priority));$links='';$count=0;foreach($priority as $target){if($target===$slug||!isset($pages[$target]))continue;$links.='<a href="'.esc_url(home_url('/'.$target.'/')).'">'.esc_html($pages[$target]).'<span>→</span></a>';if(++$count>=4)break;}return $content.'<section class="sk-search-links" aria-label="Related Softkom solutions"><div><p>EXPLORE RELATED SOLUTIONS</p><h2>Continue exploring what fits your business</h2><nav>'.$links.'</nav></div></section>';},80);
add_action('wp_enqueue_scripts',function(){if(!softkom_search_is_money_page())return;wp_register_style('softkom-search-discovery',false,array(),'2.0.0');wp_enqueue_style('softkom-search-discovery');wp_add_inline_style('softkom-search-discovery','.sk-search-links{font-family:Inter,system-ui,sans-serif;padding:70px 24px;background:#f8fafc;border-top:1px solid #e2e8f0}.sk-search-links>div{max-width:1180px;margin:auto}.sk-search-links p{margin:0 0 10px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.09em}.sk-search-links h2{max-width:700px;margin:0 0 28px;color:#0f172a;font-size:clamp(28px,4vw,42px);line-height:1.1;letter-spacing:-.03em}.sk-search-links nav{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.sk-search-links a{display:flex;justify-content:space-between;align-items:center;gap:15px;padding:18px 20px;background:#fff;border:1px solid #e2e8f0;border-radius:12px;color:#0f172a!important;text-decoration:none!important;font-weight:700}.sk-search-links a:hover{border-color:#93c5fd;box-shadow:0 8px 24px rgba(15,23,42,.06)}.sk-search-links a span{color:#2563eb}@media(max-width:760px){.sk-search-links nav{grid-template-columns:1fr}}');},40);
add_action('wp_head',function(){if(!softkom_search_is_money_page())return;$graph=array('@context'=>'https://schema.org','@graph'=>array(array('@type'=>'Organization','@id'=>home_url('/#organization'),'name'=>'Softkom Solutions','url'=>home_url('/'),'description'=>'South African business systems, AI automation and digital infrastructure company helping growing organisations replace manual processes and disconnected tools with scalable systems.','areaServed'=>array('@type'=>'Country','name'=>'South Africa'),'knowsAbout'=>array('AI automation','business process automation','custom business systems','workflow automation','sales automation','WhatsApp automation','AI readiness','systems integration','business systems')),array('@type'=>'WebPage','@id'=>get_permalink().'#webpage','url'=>get_permalink(),'name'=>wp_get_document_title(),'isPartOf'=>array('@type'=>'WebSite','@id'=>home_url('/#website'),'url'=>home_url('/'),'name'=>'Softkom Solutions'),'about'=>array('@id'=>home_url('/#organization')),'inLanguage'=>'en-ZA')));echo '<script type="application/ld+json">'.wp_json_encode($graph,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).'</script>'."\n";},45);
